---
- file: path=/root/rpmbuild state=directory
- file: path=/root/rpmbuild/SOURCES state=directory
- yum: name={{ item }}
  with_items:
    - gettext
    - rpm-build
    - ftp://ftp.pbone.net/mirror/ftp5.gwdg.de/pub/opensuse/repositories/home:/ikoinoba/CentOS_CentOS-6/x86_64/checkinstall-1.6.2-3.el6.1.x86_64.rpm
