---
- debug:
    msg: Hello {{ ansible_distribution }}
- file: path={{ build_dir }} state=directory
- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
- include: CentOS.yml
  when: ansible_distribution == "CentOS"
